### ISSUE TITLE
No data for Jena (and Thuringia)

### ISSUE THREAD

**Issue by k-0** [mswart/openmensa-parsers#109]
OpenMensa (website and API) shows no data for all canteens in Jena.

**Comment by klemens** [comment]
Their TLS configuration is broken, the certificate chain is missing the intermediate certificate: https://www.ssllabs.com/ssltest/analyze.html?d=www.stw%2dthueringen.de&s=141.35.105.193&latest

And because they don't allow plain text connections, we don't get any data at all, so there are no (simple) workarounds.

I wrote them an email explaining the problem, you should be on CC.

**Comment by Roebke** [comment]
Hi, I am no developer on this project but the XML-files listed in [this issue](https://github.com/openmensa/openmensa/issues/37#issue-345543297) seem to work fine (at least for the canteens which are currently open, like Mensa Ehrenberg (Ilmenau) or Mensa Ernst Abbe Platz (Jena)). I may be wrong but for me it doesn't look like the problem has something to do with the website of the Studierendenwerk.

**Comment by klemens** [comment]
@Roebke: Seems like @mswart's server is ignoring certificate errors in some way, because their tls config is still broken. I also haven't got an answer to the email mentioned above.

So I guess let's just also ignore certificate errors (though only for www.stw-thueringen.de). :shrug: Fix incoming...
