### ISSUE TITLE
Several canteens in Hannover return prices as null

### ISSUE THREAD

**Issue by Memorion** [mswart/openmensa-parsers#13]
example query: http://openmensa.org/api/v2/canteens/7/days/2015-07-10/meals

**Comment by Memorion** [comment]
Well, I just checked all canteens for that day with an insanely ugly bash script but it looks like 80% of them return only null prices, so you just can't rely on prices or is there something wrong here?

**Comment by mswart** [comment]
It was a bug within openmensa itself: since this weekend, openmensa did not process any price information provided by the feeds. This should be fixed now, and within the next hours (or tomorrow morning) most canteens should includes price information.

Many thx for the hint, it got slipped thought our tests (wrong test data)
