### ISSUE TITLE
index-url does not work anymore

### ISSUE THREAD

**Issue by theScrabi** [mswart/openmensa-parsers#75]
I figured something was changed lately, because the Index url for my parser is not working anymore, and I get mail every day. It says it wants json now, but I still provide html.
![screen shot 2018-03-28 at 11 33 00](https://user-images.githubusercontent.com/1891273/38023348-525352a0-3282-11e8-890b-ae0ff6dad225.png)

What should I do here?

**Comment by Y0hy0h** [comment]
I just tried to look up the URL you've put into "Index-URL". It doesn't exist anymore: https://github.com/theScrabi/openmensa-parsers

Since this is the link to *your* fork(?), I suspect that you recently deleted the repo which broke the link. Can you check if that is the case?

Also I think that this issue is related more to [OpenMensa](https://github.com/openmensa/openmensa) itself rather than the parsers.

**Comment by theScrabi** [comment]
I did yes, but before it didn't work as well.

**Comment by klemens** [comment]
I guess we can close this? Currently there is no index url (that's ok) and if we have to change anything in the parser, will can change the index url to https://omfeeds.crpt.de/erlangen_nuernberg/index.json.
