### ISSUE TITLE
Change of Parsers for Canteens in Thuringia

### ISSUE THREAD

**Issue by Anarchoschnitzel** [mswart/openmensa-parsers#81]
So a couple of days ago I opened a pull request ( #79 ) for a new parser from the canteens of Studentenwerk Thüringen which should add a lot of canteens for Thuringia.
The reason I added this parser is the fact that I found out that a lot of canteens from Thuringia lack data / don't contain data at all  (e.g. Erfurt, Jena, Ilmenau) in the current OpenMensa REST API.
The question I have is: once this pull request is merged, will the new parser be available on the server for this project and if so, how can we change the data source from the already existing Thuringia Canteens to the new parsers so OpenMensa will be fed with actual Data for this canteens?

Thanks in advance and kind regards :)

**Comment by klemens** [comment]
> once this pull request is merged, will the new parser be available on the server for this project

Yes, after we merge the changes, the new parser will be available within an hour or so.

> how can we change the data source from the already existing Thuringia Canteens to the new parsers

I didn't realize until now that there are already parsers for Thüringen, but as those haven't been updated since 2016, it seems there isn't much interest in still maintaining them and so I guess there should be no problem changing them to use the new parser. However someone from the @openmensa team will have to do it.
